### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by AdnanRahman2** [JJLee2910/Car-Rental-Sytem#1]
Hello, Jang hope you are having a good day!
How can I contact you?

**Comment by AdnanRahman2** [comment]
Do you have an email?

**Comment by JJLee2910** [comment]
hi, can contact me thru here ya
    On Saturday, December 3, 2022 at 06:49:31 AM GMT+8, Adnan Rahman ***@***.***> wrote:  
 
 


Do you have an email?

**Comment by JJLee2910** [comment]
> Do you have an email?

Hi, can contact me via here ya jangjhinL@yahoo.com
